### ISSUE TITLE
ONNX Version?

### ISSUE THREAD

**Issue by msmollin** [torralba-lab/im2recipe-Pytorch#30]
First, thank you for this model and this research. It's been a big help in my process for learning ML and PyTorch.

I was wondering if it would be possible to provide your pre-trained model in an ONNX format? My end goal here would be to use it on iOS and Android, and both platforms have hardware accelerated inference engines (CoreML/Tensorflow Lite respectively.) My initial reading has lead me to believe it's more compact and generally faster to use the native solutions rather PyTorch itself on mobile. Thoughts? It appears PyTorch can output to the ONNX format, but I'm not 100% sure I understand enough of the inputs and outputs of this model to do it correctly myself.

**Comment by nhynes** [comment]
Hey @msmollin, I'm very glad that you're finding this repo useful! It's a bit out of date, as you can imagine. I'm not entirely sure whether a simple ONNX export is possible for this multi-part model. You can certainly forward the individual pieces (the CNN, the RNN, the MLP) and export them individually. IMHO, I'd probably go and rewrite it using newer sub-components like transformer and whatnot. Really it's just a dataset plus an objective that keeps distinct classes apart (e.g., the technique in https://github.com/torralba-lab/im2recipe-Pytorch/issues/14#issuecomment-445568388). 

It's been a while since I've mucked with pytorch, so I'm not confident that I can get you a solution quickly, but I still do software, and can help out if you get stuck. Please just let me know!
