### ISSUE TITLE
Asking the way to get recipe by querying img

### ISSUE THREAD

**Issue by wonsik-song** [torralba-lab/im2recipe-Pytorch#36]
Hi,
I want to test imge2recipe(querying image and response recipe).
But, I can't find imge2recipe script in git hub
How can I test imge2recipe in script??
Please guide us
Thank

**Comment by jmarintur** [comment]
In order to do that, you can check the way we extract image and recipe embeddings in test.py and then run rank.py. If you want to perform this multiple times, I recommend you to extract all the recipe embeddings first and save them. Then every time you want to get the best match in terms of recipe given an image, you just need to extract the image embedding and computing the distance against each recipe embedding you saved.
